#!/bin/bash

# Usage: ./renew_single_domain domain_directory webroot

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

. "$SCRIPT_DIR/vars"

EXIT_CODE=0

DOMAIN=$1
WEBROOT=$2

if [[ -z "$DOMAIN"  || -z "$WEBROOT" ]]; then
	echo "Usage: $0 domain path"
	exit 1
fi

if [[ ! -f "$DOMAIN/rsa/key.pem"  || (! -f "$DOMAIN/dsa/key.pem" &&  -z "$SKIP_DSA") ]]; then
	echo "Domain $DOMAIN doesn't exist!"
	exit 1
fi

if [[ ! -d "$WEBROOT" ]]; then
	echo "Webroot $WEBROOT doesn't exist!"
	exit 1
fi

for TYPE in rsa dsa; do
	if [[ "$TYPE" = "dsa" && ! -z "$SKIP_DSA" ]]; then
		echo "Skipping $TYPE certificate due to SKIP_DSA being set"
		continue
	fi

	# Make sure it actually needs renewing.
	if [[ -z "$SKIP_CHECK" && -f "$DOMAIN/$TYPE/fullchain.pem" ]]; then
		openssl x509 -checkend 2851200 -in "$DOMAIN/$TYPE/fullchain.pem" -noout 1>/dev/null
		if [ $? -eq 0 ]; then
			echo "Renewal of $TYPE certificate for $DOMAIN is not yet necessary, skipping..."
			continue
		fi
	fi

	echo "Renewing $TYPE certificate for $DOMAIN..."

	CERTOUT=$(mktemp)
	if [[ -z $CERTOUT ]]; then
		echo "Failed to create temp file"
		exit 1
	fi
	
	mkdir -p "$WEBROOT/.well-known/acme-challenge"
	acme_tiny.py --disable-check --account-key "$ACCOUNT_KEY_PATH" --contact "$CONTACT" --csr "$DOMAIN/$TYPE/csr.pem" --acme-dir "$WEBROOT/.well-known/acme-challenge" > "$CERTOUT"
	if [[ $? -eq 0 ]]; then
		cat "$CERTOUT" | "$SCRIPT_DIR/remove_root" > "$DOMAIN/$TYPE/fullchain.pem"
		rm -f "$CERTOUT"
		echo "Completed."
		EXIT_CODE=2
	else
		echo "Renewal of $TYPE certificate for $DOMAIN failed, exit status $?"
		EXIT_CODE=1
	fi

done

exit $EXIT_CODE
